export const portfolioData = {
  name: "Serge Zimmermann",
  title: "Directeur de Projet - Manager de Transition",
  tagline: "Un pilote solide pour vos projets",
  headline: "Je protège vos budgets & sécurise vos engagements",
  summary:
    "Directeur de projet avec 32 ans d'expérience en pilotage de programmes complexes dans le respect du triptique coûts/qualité/délais. Spécialisé en transformation SI, conduite du changement et management de transition pour secteurs Retail, Banque, Administration, ESN, Industrie, Assurance et Bailleurs sociaux. Capacité à reprendre en main des programmes en difficulté et à coordonner des équipes multidisciplinaires.",
  contact: {
    email: "serge@z-consult.fr",
    phone: "+33 6 66 26 14 62",
    location: "Lambersart, France",
    calendly: "https://calendly.com/z-consult",
  },
  social: {
    linkedin: "www.linkedin.com/in/serge-zimmermann-135a1774",
    github: "",
    email: "serge@z-consult.fr",
    malt: "https://www.malt.fr/profile/sergezimmermann1",
    collective: "https://app.collective.work/network-invitation/serge-zimmermann",
  },
  experience: [
    {
      company: "Roquette Frères",
      sector: "(Industrie)",
      role: "Directeur de Programme",
      duration: "2022 - 2025",
      technologies: ["SalesForce (Sales Cloud, Service Cloud, Pardot)", "SAP", "CPQ", "NUXEO", "EDICOM"],
      achievements: [
        "Cadrage et pilotage du programme d'intégration SalesForce (600 utilisateurs, 6M€, 4 ans) suite au rachat d'IFF par Roquette : quotation, pricing, product lifecycle mgt, customer lifecycle mgt, sales funnel, process services",
        "Cadrage et pilotage du projet « quotation » (intégration CPQ) : RFP CPQ/choix intégrateur, définition de la roadmap, pilotage de 2 centres de services, 4 business analystes, tests leader, change manager, AMOA",
        "Reprise en main de la roadmap CRM SalesForce (Sales Cloud, Service Cloud, Pardot) et finalisation sur 3 ans, gestion du budget et des engagements, pilotage de l'intégrateur",
        "Cadrage et pilotage du projet de facturation électronique pour 5 pays (PDP : EDICOM)",
        "Pilotage projet YARD pour la supply chain : automatisation du parcours des camions sur site pilote, en lien avec SAP + solution de gestion documentaire (2 ans)",
        "Pilotage du projet d'upgrade de l'outil de gestion documentaire NUXEO",
        "Pilotage coûts/qualité/délais, études de faisabilité diverses",
      ],
    },
    {
      company: "Plusieurs entreprises",
      sector: "",
      role: "Manager IT Freelance en Temps Partagé",
      duration: "2020 - 2022",
      technologies: ["Audit DSI", "SaaS", "APIs", "Roadmap IT"],
      achievements: [
        "CCI de Lille : audit permettant de déterminer la meilleure méthodologie de développement au sein de la DSI",
        "ASTAV : audit sur l'externalisation de la solution et préconisations vers le mode SaaS et impacts sur les postes de travail",
        "Centre l'Espoir : audit et préconisations sur la gestion des ressources internes et externes",
        "Kaefer Wanner : audit et préconisations sur la roadmap IT",
        "ID Kids : audit et préconisations sur l'APIsation de l'entreprise, aide organisationnelle de la responsable de domaine",
      ],
    },
    {
      company: "GIE LA MÉTA",
      sector: "(GIE LMH / VILOGIA - Bailleur social)",
      role: "Directeur de Programme Freelance",
      duration: "2020 - 2022",
      technologies: ["Construction SI", "UX", "BI", "Infrastructure", "Sécurité", "TMA"],
      achievements: [
        "Construction du Système d'Information 'from scratch' en relation avec la Direction Générale",
        "Élaboration de la stratégie de mise en œuvre du SI, lotissement, macro planning, définition et pilotage des budgets et des risques",
        "Pilotage des prestataires : UX, étude, développement, infrastructure, recette, sécurité, BI, TMA",
        "Élaboration des appels d'offres, analyse des offres, négociation des contrats et avenants",
        "Préparation et animation des comités de pilotage Méta/bailleurs, comités arbitrage et conduite du changement",
      ],
    },
    {
      company: "LSA Courtage / Assurpeople.com",
      sector: "(Courtier en assurance)",
      role: "Directeur du Service Informatique - Manager de Transition",
      duration: "2019 - 2020",
      technologies: ["Méthodologie projet", "Reporting qualité"],
      achievements: [
        "Audit et proposition de réorganisation de la DSI sur la base d'entretiens individuels IT et métier (évolution de 10 à 15 personnes)",
        "Mise en place des pôles : AMOA, Build, RUN, Infra",
        "Recrutement des ressources : développeurs, ingénieur d'étude, technicien d'exploitation et DSI",
        "Projets en partenariat avec le comité de direction et le PDG (intégration de partenaires, ouverture de la branche pro LSA)",
        "Mise en place progressive d'une méthodologie projet adaptée et du reporting qualité",
      ],
    },
    {
      company: "Thales Service pour Eurotunnel",
      sector: "",
      role: "Directeur de Projet Freelance",
      duration: "2019",
      technologies: ["TOGAF", "PPM", "PMP", "TMA"],
      achievements: [
        "Rédaction de propositions techniques pour le démarrage du projet SMART CHECKIN (transformation SI péage) : urbanisation et architecture d'entreprise (référentiel TOGAF)",
        "Coaching du chef de projet dans le pilotage de la TMA et des projets sensibles (Brexit, migration Windows 10 / Oracle 12)",
        "Apport méthodologique : mise en place du PPM spécifique Thales, mise à jour du PMP",
        "Animation des comités techniques, projet et de suivi TMA (COSUI), pilotage (COPIL)",
      ],
    },
    {
      company: "Auchan DOSI DPC",
      sector: "(Retail)",
      role: "Responsable de Domaine Textile DSI - Manager de Transition",
      duration: "2017 - 2018",
      technologies: ["Oracle RMS 13 (RMS, RPM, allocations, réappro)", "TXT", "Infolog"],
      achievements: [
        "Supply Chain en mode piloté pour l'univers textile (2 Mds € de CA) sur base des composants Oracle RMS 13, connectés aux progiciels TXT et Infolog",
        "Stabilisation du système en production : correction des anomalies, pilotage de task forces avec le métier, mise en place de pilotes",
        "Mise en place de benchs pour l'augmentation des volumétries (réappro jusqu'à 1 million de pièces)",
        "Déploiement de tous les marchés textiles : 9 marchés, 8 pays déployés + 2 en cours (Russie et Ukraine)",
        "Pilotage d'une équipe de 2 CP senior, 4 responsables d'application, 4 experts techniques et fonctionnels, budget 1,5M€ (build et run)",
        "Participation au CODIR hebdomadaire, travail sur les budgets, mise en place de centres de services",
      ],
    },
    {
      company: "Adeo, Groupe Leroy Merlin",
      sector: "(Retail)",
      role: "PMO Programme Freelance",
      duration: "2016",
      technologies: ["Lean IT", "PMO", "PIM", "DAM"],
      achievements: [
        "Assistance au pilotage d'un programme de transformation SI (PIM, DAM, Meti CA/Supply/Store) pour 4 BU (Italie, Espagne, Portugal, France), 4,5M€",
        "Animation du d-stum et des chantiers d'amélioration continue dans le cadre du Lean IT",
        "Proposition et mise en place d'une nouvelle organisation projet : COPRO internes, animation des DP en transverse, plan de charge des ressources partagées",
        "Challenge des estimations et des RAF, création et suivi des plannings projets",
        "Coaching des directeurs de projet et managers, assistance des acteurs en faiblesse",
      ],
    },
    {
      company: "Apside",
      sector: "(ESN)",
      role: "Directeur de Projet",
      duration: "2014 - 2015",
      technologies: ["Engagement de résultat", "Avant-vente", "Angular JS"],
      achievements: [
        "Direction de projet pour RCI / Renault Banque Brésil et Allemagne : équipe de 15 personnes, projet spécifique sur Angular JS",
        "Recadrage du projet pour passer d'un mode assistance technique à un mode engagement de résultat",
        "Rédaction de propositions commerciales pour des prestations de MCO pour le Brésil et l'Allemagne",
        "Animation d'un comité stratégique avec la DSI de RCI Banque petits pays",
        "Audit de prestations à engagements de résultat sur l'ensemble du territoire et coaching de chefs de projet",
      ],
    },
    {
      company: "Open",
      sector: "(ESN)",
      role: "Ingénieur Développeur Oracle puis Chef de Projet et Directeur de Projet",
      duration: "1996 - 2014",
      technologies: ["Oracle Developer", "TMA"],
      achievements: [
        "Commission européenne : chef de projet sur projet Oracle Developer de 1 500 j, 3 ans",
        "Camaïeu femme : chef de projet sur TMA de 8 personnes, 3 ans",
        "CUD Lille : chef de projet sur projet de développement de 500 j",
        "Contentia : chef de projet sur projet de refonte du SI, 1,5 an",
        "KITS/Castorama : chef de projet senior sur TMA de 25 personnes, 2 ans",
        "Euro information développement : chef de projet et directeur de projet sur centre de service de 20 personnes, 3 ans",
      ],
    },
    {
      company: "Cylande",
      sector: "(Éditeur de logiciel)",
      role: "Développeur Delphi",
      duration: "1994 - 1996",
      technologies: ["Delphi"],
      achievements: [
        "Développement Delphi sur une application d'encaissement et de gestion de stock",
      ],
    },
  ],
  skillsByCategory: {
    "Pilotage de Programmes": [
      "Programmes multi-millions",
      "Reprise en main de programmes",
      "Planification macro",
      "Gestion budgets et risques",
      "Comités de suivi et arbitrage",
    ],
    "Management & Transformation": [
      "Management de transition",
      "Audit DSI",
      "Conduite du changement",
      "Montée en compétences",
      "Coaching d'équipes",
    ],
    Méthodologies: [
      "Cycle en V",
      "Agile (Scrum, Kanban)",
      "TOGAF",
      "Lean IT",
      "PPM & PMP",
    ],
    Technologies: [
      "SalesForce",
      "Oracle",
      "SAP",
      "NUXEO",
      "Développement (Delphi, Angular)",
    ],
    "Contractualisation": [
      "Appels d'offres",
      "Analyse d'offres",
      "Négociation de contrats",
      "RFP",
    ],
    "Secteurs d'Expertise": [
      "Retail (textile, bricolage)",
      "Banque",
      "Administration",
      "ESN",
      "Industrie",
      "Assurance",
      "Bailleurs sociaux",
    ],
  },
  education: [
    {
      school: "Université Lille 1",
      degree: "Maîtrise Informatique",
      year: "1984",
      location: "Lille, France",
    },
  ],
  languages: [
    { language: "Français", level: "Natif" },
    { language: "Anglais", level: "Professionnel" },
  ],
};